
from core.setup.encryption import decrypt_value, encrypt_value
from core.setup.service import SETUP_STEPS, generate_env_content


class TestEncryption:
    def test_encrypt_decrypt_roundtrip(self):
        original = "sk-ant-api-key-test-12345"
        encrypted = encrypt_value(original)
        assert encrypted != original
        decrypted = decrypt_value(encrypted)
        assert decrypted == original

    def test_encrypt_produces_different_ciphertexts(self):
        value = "same-value"
        enc1 = encrypt_value(value)
        enc2 = encrypt_value(value)
        assert enc1 != enc2

    def test_decrypt_empty_string(self):
        result = decrypt_value("")
        assert result == ""

    def test_encrypt_special_characters(self):
        original = "key-with-special=chars&symbols/plus+more"
        encrypted = encrypt_value(original)
        decrypted = decrypt_value(encrypted)
        assert decrypted == original

    def test_encrypt_multiline_value(self):
        original = "-----BEGIN RSA KEY-----\nMIIEpA...base64...\n-----END RSA KEY-----"
        encrypted = encrypt_value(original)
        decrypted = decrypt_value(encrypted)
        assert decrypted == original


class TestSetupSteps:
    def test_steps_are_defined(self):
        assert len(SETUP_STEPS) == 7

    def test_steps_have_correct_order(self):
        assert SETUP_STEPS[0] == "welcome"
        assert SETUP_STEPS[1] == "ai_provider"
        assert SETUP_STEPS[-1] == "review"

    def test_all_steps_are_strings(self):
        for step in SETUP_STEPS:
            assert isinstance(step, str)
            assert len(step) > 0


class TestEnvGeneration:
    def test_generate_env_with_single_category(self):
        configs = [
            {
                "key": "GITHUB_TOKEN",
                "value": "ghp_test123",
                "category": "github",
                "display_name": "GitHub Token",
                "is_sensitive": True,
            },
        ]
        result = generate_env_content(configs)
        assert "GITHUB_TOKEN=ghp_test123" in result
        assert "GitHub Configuration" in result

    def test_generate_env_with_multiple_categories(self):
        configs = [
            {
                "key": "GITHUB_TOKEN",
                "value": "ghp_test",
                "category": "github",
                "display_name": "Token",
                "is_sensitive": True,
            },
            {
                "key": "SLACK_BOT_TOKEN",
                "value": "xoxb-test",
                "category": "slack",
                "display_name": "Token",
                "is_sensitive": True,
            },
            {
                "key": "CLI_PROVIDER",
                "value": "claude",
                "category": "ai_provider",
                "display_name": "Provider",
                "is_sensitive": False,
            },
        ]
        result = generate_env_content(configs)
        assert "GITHUB_TOKEN=ghp_test" in result
        assert "SLACK_BOT_TOKEN=xoxb-test" in result
        assert "CLI_PROVIDER=claude" in result

    def test_generate_env_empty_configs(self):
        result = generate_env_content([])
        assert "Groote AI Configuration" in result
        assert "Generated by Setup Wizard" in result

    def test_generate_env_has_header(self):
        result = generate_env_content([])
        lines = result.strip().split("\n")
        assert lines[0] == "# Groote AI Configuration"
        assert lines[1] == "# Generated by Setup Wizard"

    def test_generate_env_category_grouping(self):
        configs = [
            {
                "key": "JIRA_URL",
                "value": "https://test.atlassian.net",
                "category": "jira",
                "display_name": "URL",
                "is_sensitive": False,
            },
            {
                "key": "JIRA_EMAIL",
                "value": "test@test.com",
                "category": "jira",
                "display_name": "Email",
                "is_sensitive": False,
            },
        ]
        result = generate_env_content(configs)
        assert "Jira Configuration" in result
        jira_section = result.split("Jira Configuration")[1]
        assert "JIRA_URL=https://test.atlassian.net" in jira_section
        assert "JIRA_EMAIL=test@test.com" in jira_section
