import type { StepDefinition } from "./types";

export const SETUP_STEPS: StepDefinition[] = [
  {
    id: "welcome",
    title: "WELCOME",
    description: "Check infrastructure and start setup",
    icon: "Rocket",
    skippable: false,
    fields: [],
  },
  {
    id: "ai_provider",
    title: "AI_PROVIDER",
    description: "Configure your AI execution engine",
    icon: "Brain",
    skippable: false,
    validationService: "anthropic",
    fields: [
      {
        key: "CLI_PROVIDER",
        label: "Provider",
        placeholder: "claude",
        sensitive: false,
        required: true,
        helpText: "Choose 'claude' or 'cursor'",
      },
      {
        key: "ANTHROPIC_API_KEY",
        label: "Anthropic API Key",
        placeholder: "sk-ant-...",
        sensitive: true,
        required: false,
        helpText: "Optional if using ~/.anthropic credentials",
      },
      {
        key: "CLAUDE_MODEL_COMPLEX",
        label: "Complex Model",
        placeholder: "opus",
        sensitive: false,
        required: false,
        helpText: "For planning tasks (opus/sonnet)",
      },
      {
        key: "CLAUDE_MODEL_EXECUTION",
        label: "Execution Model",
        placeholder: "sonnet",
        sensitive: false,
        required: false,
        helpText: "For code execution (sonnet/haiku)",
      },
    ],
  },
  {
    id: "github_oauth",
    title: "GITHUB",
    description: "Create a GitHub App for repository automation",
    icon: "Github",
    skippable: true,
    stepType: "oauth_setup",
    oauthPlatform: "github",
    validationService: "github_oauth",
    instructions: [
      {
        step: 1,
        title: "Go to GitHub Settings",
        description:
          "Navigate to GitHub > Settings > Developer settings > GitHub Apps > New GitHub App",
        link: "https://github.com/settings/apps/new",
      },
      {
        step: 2,
        title: "Fill App Details",
        description:
          "Name: your-org-groote, Homepage URL: your domain, Callback URL: {origin}/oauth/callback/github",
      },
      {
        step: 3,
        title: "Set Permissions",
        description: "Repository: Read & Write, Issues: Read & Write, Pull Requests: Read & Write",
      },
      {
        step: 4,
        title: "Generate Private Key",
        description: "After creation, generate a private key and paste it below",
      },
      {
        step: 5,
        title: "Copy Credentials",
        description: "Copy the App ID, Client ID, and Client Secret into the fields below",
      },
    ],
    fields: [
      {
        key: "GITHUB_APP_ID",
        label: "App ID",
        placeholder: "123456",
        sensitive: false,
        required: true,
        helpText: "Shown on the GitHub App settings page",
      },
      {
        key: "GITHUB_CLIENT_ID",
        label: "Client ID",
        placeholder: "Iv1.abc123...",
        sensitive: false,
        required: true,
      },
      {
        key: "GITHUB_CLIENT_SECRET",
        label: "Client Secret",
        placeholder: "your-client-secret",
        sensitive: true,
        required: true,
      },
      {
        key: "GITHUB_PRIVATE_KEY",
        label: "Private Key (PEM)",
        placeholder: "-----BEGIN RSA PRIVATE KEY-----\n...",
        sensitive: true,
        required: true,
        multiline: true,
      },
      {
        key: "GITHUB_WEBHOOK_SECRET",
        label: "Webhook Secret",
        placeholder: "your-webhook-secret",
        sensitive: true,
        required: false,
        helpText: "For webhook signature validation",
      },
    ],
  },
  {
    id: "jira_oauth",
    title: "JIRA",
    description: "Create a Jira OAuth app for project management",
    icon: "ClipboardList",
    skippable: true,
    stepType: "oauth_setup",
    oauthPlatform: "jira",
    validationService: "jira_oauth",
    instructions: [
      {
        step: 1,
        title: "Go to Atlassian Developer Console",
        description: "Create a new OAuth 2.0 (3LO) app",
        link: "https://developer.atlassian.com/console/myapps/",
      },
      {
        step: 2,
        title: "Configure OAuth 2.0",
        description: "Add callback URL: {origin}/oauth/callback/jira",
      },
      {
        step: 3,
        title: "Set Scopes",
        description:
          "Add scopes: read:jira-work, write:jira-work, read:jira-user, manage:jira-project",
      },
      {
        step: 4,
        title: "Copy Credentials",
        description: "Copy the Client ID and Secret from the app settings",
      },
    ],
    fields: [
      {
        key: "JIRA_CLIENT_ID",
        label: "Client ID",
        placeholder: "your-jira-client-id",
        sensitive: false,
        required: true,
      },
      {
        key: "JIRA_CLIENT_SECRET",
        label: "Client Secret",
        placeholder: "your-jira-client-secret",
        sensitive: true,
        required: true,
      },
    ],
  },
  {
    id: "slack_oauth",
    title: "SLACK",
    description: "Create a Slack App for chat notifications",
    icon: "MessageSquare",
    skippable: true,
    stepType: "oauth_setup",
    oauthPlatform: "slack",
    validationService: "slack_oauth",
    instructions: [
      {
        step: 1,
        title: "Create a Slack App",
        description: "Go to api.slack.com/apps and click Create New App",
        link: "https://api.slack.com/apps",
      },
      {
        step: 2,
        title: "Configure OAuth & Permissions",
        description:
          "Add redirect URL: {origin}/oauth/callback/slack. Add scopes: chat:write, commands, app_mentions:read",
      },
      {
        step: 3,
        title: "Copy Credentials",
        description: "Copy Client ID and Client Secret from Basic Information page",
      },
    ],
    fields: [
      {
        key: "SLACK_CLIENT_ID",
        label: "Client ID",
        placeholder: "your-slack-client-id",
        sensitive: false,
        required: true,
      },
      {
        key: "SLACK_CLIENT_SECRET",
        label: "Client Secret",
        placeholder: "your-slack-client-secret",
        sensitive: true,
        required: true,
      },
      {
        key: "SLACK_SIGNING_SECRET",
        label: "Signing Secret",
        placeholder: "your-signing-secret",
        sensitive: true,
        required: false,
        helpText: "For request signature validation",
      },
    ],
  },
  {
    id: "sentry",
    title: "SENTRY",
    description: "Connect Sentry for error tracking and alerts",
    icon: "AlertTriangle",
    skippable: true,
    validationService: "sentry",
    fields: [
      {
        key: "SENTRY_AUTH_TOKEN",
        label: "Auth Token",
        placeholder: "your-auth-token",
        sensitive: true,
        required: true,
        helpText: "sentry.io/settings/auth-tokens",
      },
      {
        key: "SENTRY_DSN",
        label: "DSN",
        placeholder: "https://xxx@sentry.io/xxx",
        sensitive: true,
        required: false,
        helpText: "Project DSN for error reporting",
      },
      {
        key: "SENTRY_ORG_SLUG",
        label: "Organization Slug",
        placeholder: "your-org",
        sensitive: false,
        required: false,
      },
    ],
  },
  {
    id: "review",
    title: "REVIEW",
    description: "Review configuration and complete setup",
    icon: "CheckCircle",
    skippable: false,
    fields: [],
  },
];
