import type { StepDefinition } from "./types";

export const SETUP_STEPS: StepDefinition[] = [
  {
    id: "welcome",
    title: "WELCOME",
    description: "Check infrastructure and start setup",
    icon: "Rocket",
    skippable: false,
    fields: [],
  },
  {
    id: "ai_provider",
    title: "AI_PROVIDER",
    description: "Configure your AI execution engine",
    icon: "Brain",
    skippable: false,
    validationService: "anthropic",
    fields: [
      {
        key: "CLI_PROVIDER",
        label: "Provider",
        placeholder: "claude",
        sensitive: false,
        required: true,
        helpText: "Choose 'claude' or 'cursor'",
      },
      {
        key: "ANTHROPIC_API_KEY",
        label: "Anthropic API Key",
        placeholder: "sk-ant-...",
        sensitive: true,
        required: true,
        helpText: "Get from console.anthropic.com",
      },
      {
        key: "CLAUDE_MODEL_COMPLEX",
        label: "Complex Model",
        placeholder: "opus",
        sensitive: false,
        required: false,
        helpText: "For planning tasks (opus/sonnet)",
      },
      {
        key: "CLAUDE_MODEL_EXECUTION",
        label: "Execution Model",
        placeholder: "sonnet",
        sensitive: false,
        required: false,
        helpText: "For code execution (sonnet/haiku)",
      },
    ],
  },
  {
    id: "github",
    title: "GITHUB",
    description: "Connect GitHub for repository and issue automation",
    icon: "Github",
    skippable: true,
    validationService: "github",
    fields: [
      {
        key: "GITHUB_TOKEN",
        label: "Personal Access Token",
        placeholder: "ghp_...",
        sensitive: true,
        required: true,
        helpText: "github.com/settings/tokens with repo scope",
      },
      {
        key: "GITHUB_WEBHOOK_SECRET",
        label: "Webhook Secret",
        placeholder: "your-webhook-secret",
        sensitive: true,
        required: false,
        helpText: "For webhook signature validation",
      },
    ],
  },
  {
    id: "jira",
    title: "JIRA",
    description: "Connect Jira for ticket and project management",
    icon: "ClipboardList",
    skippable: true,
    validationService: "jira",
    fields: [
      {
        key: "JIRA_URL",
        label: "Jira URL",
        placeholder: "https://company.atlassian.net",
        sensitive: false,
        required: true,
        helpText: "Your Atlassian instance URL",
      },
      {
        key: "JIRA_EMAIL",
        label: "Email",
        placeholder: "agent@company.com",
        sensitive: false,
        required: true,
      },
      {
        key: "JIRA_API_TOKEN",
        label: "API Token",
        placeholder: "your-api-token",
        sensitive: true,
        required: true,
        helpText: "id.atlassian.com/manage-profile/security/api-tokens",
      },
    ],
  },
  {
    id: "slack",
    title: "SLACK",
    description: "Connect Slack for chat notifications and commands",
    icon: "MessageSquare",
    skippable: true,
    validationService: "slack",
    fields: [
      {
        key: "SLACK_BOT_TOKEN",
        label: "Bot Token",
        placeholder: "xoxb-...",
        sensitive: true,
        required: true,
        helpText: "From api.slack.com/apps > OAuth & Permissions",
      },
      {
        key: "SLACK_SIGNING_SECRET",
        label: "Signing Secret",
        placeholder: "your-signing-secret",
        sensitive: true,
        required: false,
        helpText: "For request signature validation",
      },
    ],
  },
  {
    id: "sentry",
    title: "SENTRY",
    description: "Connect Sentry for error tracking and alerts",
    icon: "AlertTriangle",
    skippable: true,
    validationService: "sentry",
    fields: [
      {
        key: "SENTRY_AUTH_TOKEN",
        label: "Auth Token",
        placeholder: "your-auth-token",
        sensitive: true,
        required: true,
        helpText: "sentry.io/settings/auth-tokens",
      },
      {
        key: "SENTRY_DSN",
        label: "DSN",
        placeholder: "https://xxx@sentry.io/xxx",
        sensitive: true,
        required: false,
        helpText: "Project DSN for error reporting",
      },
      {
        key: "SENTRY_ORG_SLUG",
        label: "Organization Slug",
        placeholder: "your-org",
        sensitive: false,
        required: false,
      },
    ],
  },
  {
    id: "review",
    title: "REVIEW",
    description: "Review configuration and complete setup",
    icon: "CheckCircle",
    skippable: false,
    fields: [],
  },
];
